name: gunsayaci
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Ortak bağımlılıklar:
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2

  # Proje 1 bağımlılıkları:
  win32: 5.1.1
  nb_utils: ^7.0.7
  flutter_svg: ^1.0.0
  table_calendar: ^3.0.9
  intl: ^0.19.0 # Sürüm güncellendi
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.3

  # Proje 2 bağımlılıkları:
  path: any
  get_it: ^7.6.0
  provider: ^6.0.5
  sqflite: ^2.2.8+4
  fluttertoast: ^8.2.2
  # url_launcher: ^6.1.11
  flutter_easyloading: ^3.0.5
  flutter_native_splash: ^2.3.0
  flutter_local_notifications: ^17.2.4
  permission_handler: ^10.4.3
  timezone: ^0.9.2
  flutter_localizations:
    sdk: flutter
  easy_localization: ^3.0.2
  fl_chart: ^0.69.2
  http: ^1.2.0
  html: ^0.15.0
  flutter_html: ^3.0.0-beta.2  # Beta sürümü
  # flutter_svg: ^2.0.0  # Flutter_html beta sürümüyle uyumlu
  url_launcher: ^6.3.1
  open_file: ^3.0.3
  path_provider: ^2.0.11
  clipboard: ^0.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.1
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    # Proje 1 varlıkları:
    - assets/images/
    - assets/svgs/
    - assets/svgs/github-mark.svg

    # Proje 2 varlıkları:
    - assets/translations/

  fonts:
    # Proje 1 fontları (Sora):
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora-Light.ttf
        - asset: assets/fonts/Sora-Regular.ttf
        - asset: assets/fonts/Sora-Medium.ttf
          weight: 300
        - asset: assets/fonts/Sora-Bold.ttf
        - asset: assets/fonts/Sora-ExtraLight.ttf
        - asset: assets/fonts/Sora-ExtraBold.ttf
          weight: 700

    # Proje 2 fontları (Poppins):
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700